config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:create]
  end

  scope :admin do
    namespace :messaging do
      resources :queues, param: :slug do
        resources :messages, only: [:show], controller: 'queues/messages'
        resources :handlers, only: [:show], controller: 'queues/handlers'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/messaging/command.rb
module Models
  module Messaging
    class Command < Message
    end
  end
end

app/models/messaging/event.rb
module Models
  module Messaging
    class Event < Message
    end
  end
end

app/models/messaging/message.rb
module Models
  module Messaging
    class Message < ::ApplicationRecord
      self.table_name = 'messaging_messages'

      STATUS = {
        unhandled: 'unhandled',
        handling: 'handling',
        handled: 'handled',
        failed: 'failed'
      }.freeze

      attribute :status, :text, default: STATUS[:unhandled]
      attribute :attempts_count, :integer, default: 0
      attribute :attempts_max, :integer, default: 1

      belongs_to :queue, foreign_key: 'queue_id', class_name: '::Models::Messaging::Queue'
      belongs_to :account
      belongs_to :user
      belongs_to :messageable, polymorphic: true

      has_many :attempts, class_name: '::Models::Messaging::Message::Attempt', dependent: :destroy

      class Attempt < ApplicationRecord
        self.table_name = 'messaging_message_attempts'

        validates :successful, inclusion: { in: [true, false] }

        validates :error_class_name, :error_message, :error_backtrace, presence: true, unless: :successful?
        validates :error_class_name, :error_message, :error_backtrace, absence: true, if: :successful?

        belongs_to :message, foreign_key: 'message_id', class_name: '::Models::Messaging::Message'
      end

      validates :account_id, presence: true
      validates :user_id, presence: true
      validates :type, presence: true
      validates :messageable_type, presence: true
      validates :messageable_id, presence: true
      validates :body_class_name, presence: true
      validates :body_json, presence: true, unless: -> { body_json == {} }
      validates :status, presence: true

      validates :attempts_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
      validates :attempts_max, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

      validate :validate_attempts_count_not_greater_than_attempts_max
      def validate_attempts_count_not_greater_than_attempts_max
        if attempts_count > attempts_max
          errors.add(:attempts_count, 'cannot be greater than attempts_max')
        end
      end

      after_initialize :set_default_queue, if: :new_record?

      def set_default_queue
        self.queue ||= Queue.default
      end

      before_validation :set_account_id

      def set_account_id
        self.account_id ||= messageable.account_id if messageable.respond_to?(:account_id)
      end

      def body=(body)
        self.body_class_name = body.class.name
        self.body_json = JSON.parse(body.to_json)
      end

      def body
        body_class_name.constantize.decode_json(body_json.to_json)
      end
    end
  end
end

app/models/messaging/queue.rb
module Models
  module Messaging
    class Queue < ::ApplicationRecord
      self.table_name = 'messaging_queues'

      DEFAULT_NAME = 'default'

      def self.default_id
        default.id
      end

      def self.default
        find_or_create_by(name: DEFAULT_NAME)
      end

      validates :lock_version, presence: true, numericality: { only_integer: true }
      validates :name, presence: true, uniqueness: true

      has_many :messages, -> { order(created_at: :asc) }
    end
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ::ApplicationController
    protect_from_forgery with: :null_session

    def create
      user = User.create(email: user_params[:email])

      render json: user, status: :created
    rescue User::Error => e
      render json: { errors: e.message }, status: :unprocessable_entity
    end

    private

    def user_params
      params.require(:user).permit(:email)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messaging/queues/handlers_controller.rb
module Messaging
  module Queues
    class HandlersController < ::ApplicationController
      def show
        @queues = Models::Queue.all
        queue = @queues.find { |q| q.slug == params[:queue_slug] }

        handlers = queue.handlers
        handler = handlers.find { |h| h.slug == params[:id] }

        handler_messages = find_handler_messages(
          queue_id: queue.id,
          status: params[:status],
          order: params[:order],
          limit: params[:limit])


        render locals: {
          queues: @queues,
          queue: queue,
          handler: handler,
          handler_messages: handler_messages,
          statuses: Models::Job::STATUS,
          status_counts: count_handler_messages_by_status
        }
      end

      def find_handler_messages(queue_id:, status: nil, order: nil, limit: nil)
        messages = Models::Job.where(queue_id: queue_id)
        messages = messages.where(status: status) if status.present?
        messages = messages.order(created_at: order.to_sym) if order.present?
        messages = messages.limit(limit.to_i) if limit.present? && limit.to_i.positive?

        messages
      end

      def count_handler_messages_by_status
        Models::Job
          .where(status: Models::Job::STATUS.keys)
          .group(:status)
          .count
          .transform_keys(&:to_sym)
      end
    end
  end
end

app/controllers/messaging/queues/messages_controller.rb
module Messaging
  module Queues
    class MessagesController < ::ApplicationController
      def show
        @queues = Models::Queue.all
        queue = @queues.find { |q| q.slug == params[:queue_slug] }
        message = queue.messages.find_by!(id: params[:id])

        render locals: {
          queues: @queues,
          queue: queue,
          message: message
        }
      end

      # def index
      #   queues = Models::Queue.all
      #   queue = queues.find_by!(slug: params[:queue_slug])

      #   jobs = Models::Job.where(queue_id: queue.id)

      #   statuses = Models::Job::STATUS
      #   status_counts = count_jobs_by_status(statuses.keys)

      #   messages = find_messages(
      #     queue_id: params[:queue_id],
      #     status: params[:status],
      #     order: params[:order],
      #     limit: params[:limit])

      #   render locals: {
      #     queues: queues, statuses: statuses, status_counts: status_counts, messages: messages
      #   }
      # end

    end
  end
end

app/views/layouts/_content.html.erb
<div class="content">
    <%= yield %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p>Copyright 2023</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= yield :breadcrumb %>
</header>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <% @queues.each do |queue| %>
      <li>
        <%= link_to queue.name, messaging_queue_path(queue.slug) %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Message Driven App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="main-content">
        <%= render 'layouts/navbar' %>
        <%= render 'layouts/content' %>
      </div>
      <%= render 'layouts/footer' %>
    </main>
  </body>
</html>

app/views/messaging/queues/handlers/show.html.erb
<% content_for :breadcrumb do %>
    queue > <%= queue.name %> > handler > <%= handler.name %>
<% end %>

<h1><%= handler.name %> Handler</h1>

<h2>Statuses</h2>

<% statuses.each do |key, value| %>
    <div class="status">
        <%= link_to "#{value} (#{status_counts[key] || 0})", messaging_queue_handler_path(status: key) %>
    </div>
<% end %>

<h2>Messages</h2>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Scheduled for</th>
      <th>Attempts count</th>
      <th>Attempts max</th>
      <th>Attempts</th>
    </tr>
  </thead>
  <tbody>
    <% handler_messages.each do |handler_message| %>
      <tr>
        <td><%= handler_message.id %></td>
        <td><%= handler_message.status %></td>
        <td><%= handler_message.priority %></td>
        <td><%= handler_message.scheduled_for %></td>
        <td><%= handler_message.attempts_count %></td>
        <td><%= handler_message.attempts_max %></td>
        <td><%= 'Attempts' %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messaging/queues/messages/index.html.erb
<%= stylesheet_link_tag 'messaging/application', media: 'all' %>

<div class="container">
    <h1>Queues</h1>

    <% queues.each do |queue| %>
        <div class="queue">
            <%= queue.name %>
        </div>
    <% end %>

    <h1>Statuses</h1>

    <% statuses.each do |key, value| %>
        <div class="status">
            <%= link_to "#{value} (#{status_counts[key] || 0})", messaging_messages_path(status: key) %>
        </div>
    <% end %>

    <h1>Messages</h1>

    <% messages.each do |message| %>
        <div class="message">
            <div class="header"><%= message.name %></div>
            <div class="body">
                <div class="preview">
                    <% json_data = message.read_attribute(:body) %>
                    <% if json_data.is_a?(Hash) %>
                        <%= JSON.pretty_generate(json_data, indent: '    ').html_safe %>
                    <% else %>
                        Invalid JSON data
                    <% end %>
                </div>
                <div class="details">
                    <span>Status: <%= message.status %></span>
                    <span>Queue: <%= message.queue.name %></span>
                    <% if message.messageable.is_a?(User) %>
                        <span>User: <%= message.messageable.name %></span>
                    <% elsif message.messageable.is_a?(Account) %>
                        <span>Account: <%= message.messageable.name %></span>
                    <% end %>
                    <span>Attempts: <%= message.attempts_count %>/<%= message.attempts_max %></span>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/messaging/queues/messages/show.html.erb
<h1>Message ID: <%= message.id %></h1>

<p>Type: <%= message.type %></p>
<p>Body: <%= message.body %></p>
<p>Created at: <%= message.created_at %></p>
<p>Updated at: <%= message.updated_at %></p>

<h2>Handler Messages</h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Attempts count</th>
      <th>Attempts max</th>
      <th>Attempts</th>
    </tr>
  </thead>
  <tbody>
    <% message.handler_messages.each do |handler_message| %>
      <tr>
        <td><%= handler_message.id %></td>
        <td><%= handler_message.status %></td>
        <td><%= handler_message.priority %></td>
        <td><%= handler_message.attempts_count %></td>
        <td><%= handler_message.attempts_max %></td>
        <td>
          <table>
            <thead>
              <tr>
                <th>Attempt ID</th>
                <th>Started at</th>
                <th>Ended at</th>
                <th>Successful</th>
                <th>Return value</th>
                <th>Error class name</th>
                <th>Error message</th>
                <th>Error backtrace</th>
              </tr>
            </thead>
            <tbody>
              <% handler_message.attempts.each do |attempt| %>
                <tr>
                  <td><%= attempt.id %></td>
                  <td><%= attempt.started_at %></td>
                  <td><%= attempt.ended_at %></td>
                  <td><%= attempt.successful %></td>
                  <td><%= attempt.return_value %></td>
                  <td><%= attempt.error_class_name %></td>
                  <td><%= attempt.error_message %></td>
                  <!-- <td><%= attempt.error_backtrace&.join("\n") %></td> -->
                </tr>
              <% end %>
            </tbody>
          </table>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>